blank_issues_enabled: false

contact_links:
  - name: Common Issues
    url: https://rsifewshot.readthedocs.io/en/latest/faq.html
    about: Check if your issue already has solutions
  - name: MMFewShot Documentation
    url: https://rsifewshot.readthedocs.io/en/latest/
    about: Check if your question is answered in docs
